site_name: OIDC Server Demo
site_description: Mock OIDC server 
repo_name: vdbulcke/oidc-server-demo
repo_url: https://github.com/vdbulcke/oidc-server-demo
edit_uri: edit/master/docs/

theme:
  name: material
  language: en
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: light blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/vdbulcke/oidc-server-demo


nav:
- Home: index.md
- install.md
- config.md
- user_config.md
- troubleshooting.md
- Contributing: 
  - contributing/contributing.md
  - contributing/tooling.md
  - contributing/git.md
- changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
